PRELOAD: on
LOG: off
BUCKET: 'fixed'
BUCKET_CONF:
  count: 5
BUCKET_SORTER: cheb_bucket_sort
ITERATIONS: 1
TIME_LIMIT: 10

DEBUG: '30n20b8-run.csv'
MIP_GAP: 4.0
PRESOLVE: true
WORST-SOL: false
KERNEL-GROWTH: false
REMOVE-UNSET: false
PROBLEM-KICKSTART: false
DISTILL: false
VARIABLE_RANKING: false
